//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firedump
{
    using System;
    using System.Collections.Generic;

    public partial class backup_locations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public backup_locations()
        {
            this.schedule_save_locations = new HashSet<schedule_save_locations>();
        }

        public long id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string path { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule_save_locations> schedule_save_locations { get; set; }
    }
}
