//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firedump
{
    using System;
    using System.Collections.Generic;

    public partial class logs
    {
        public long id { get; set; }
        public Nullable<long> schedule_id { get; set; }
        public long type { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> success { get; set; }

        public virtual schedules schedules { get; set; }
    }
}
