//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firedump
{
    using System;
    using System.Collections.Generic;

    public partial class schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schedules()
        {
            this.logs = new HashSet<logs>();
            this.schedule_save_locations = new HashSet<schedule_save_locations>();
            this.userinfo = new HashSet<userinfo>();
        }

        public long id { get; set; }
        public long server_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public long activated { get; set; }
        public long hours { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logs> logs { get; set; }
        public virtual sqlservers mysql_servers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule_save_locations> schedule_save_locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userinfo> userinfo { get; set; }
    }
}
